services:
  - type: web
    name: siakad-ci4
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: app.baseURL
        value: https://siakad-ci4.onrender.com/
